import type { Metadata } from "next";
import { Gilda_Display, Jost } from "next/font/google"; // Import the requested fonts
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import SmoothScroll from "@/components/SmoothScroll";

// Configure Gilda Display
const gildaDisplay = Gilda_Display({
  variable: "--font-gilda",
  subsets: ["latin"],
  weight: "400", // Gilda Display usually only comes in 400
});

// Configure Jost
const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  // Jost is a variable font, so we might not strictly need to specify weights,
  // but if we did, it handles ranges. Default is usually fine for variable fonts.
});

export const metadata: Metadata = {
  title: "Hotel Eden",
  description: "Generated by create next app",
};

import { Footer } from "@/components/layout/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gildaDisplay.variable} ${jost.variable} antialiased`}>
        <Navbar />
        <SmoothScroll>{children}</SmoothScroll>
        <Footer />
      </body>
    </html>
  );
}
